# Generated by Django 2.2 on 2023-02-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projekti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='gender',
            field=models.CharField(choices=[('M', 'Boy'), ('F', 'Girl'), ('U', 'Unisex')], max_length=1),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variations_category',
            field=models.CharField(choices=[('a', '0-3 vjec'), ('b', '3-6 vjec'), ('c', '>6 vjec')], max_length=250),
        ),
    ]
