# Generated by Django 2.2 on 2023-02-13 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projekti', '0002_auto_20230213_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='variation_value',
        ),
    ]
